README.md
package.json
packages/tronbox/package.json
packages/truffle-contract/contract.js
packages/truffle-core/lib/command.js

This PR fixes a bug causing that calling `tronbox develop` (which is an inactive command, since it does not work with TronBox), the package would execute `tronbox deploy` unexpectedly.
Also, it improves the README explaining the basic difference between testing in TronBox compared with testing in Truffle, due to the way we handle the artifacts.
Finally, it uses the last version of TronWeb.

Commands improve

---

packages/tronbox/package.json
packages/tronwrap/index.js
packages/truffle-contract/contract.js
packages/truffle-migrate/index.js

This fixes a missed parameter during the creation of contracts with a constructor which requires parameters.
Updates TronWeb to latest version.
Fix a bug during migrations. In fact, the first migration was failing and the network was updated also when not needed. This in production could mean spending money for nothing.

Fix deploy of contracts with a costructor which requires parameters

---

packages/tronbox/package.json
packages/truffle-core/lib/commands/console.js

Fix an error running the console.

Fixing console

---

packages/tronbox/package.json

Updating to tronweb 2.0.26

---

packages/tronbox/package.json
packages/truffle-core/lib/testing/testrunner.js

This fixes a typo causing tronWeb working partially in testing. Also, it updates to latest tronWeb.

Fixing an error initiatin tronWeb for testing

---

packages/tronbox/package.json

This has already been published because it was fixing a critical bug.

Fixing issue with truffle-deployer

---

package.json
packages/tronbox/package.json
packages/tronwrap/index.js
scripts/clean-all-modules.sh
scripts/purgeNode_modules.sh

Updating to soljson_v2.0, which supports `pragma ^0.4.24`

Updating solidity compiler

---

packages/tronbox/package.json
packages/tronwrap/index.js
packages/truffle-config/index.js

Adding `originalEnergyLimit` for 3.2 compatibility.

3.2 compatible

---

packages/tronbox/package.json
packages/tronwrap/index.js

This fixes a well known issue which was causing process being appended forever.

Fixed issue causing appended process

---

package.json
packages/tronwrap/constants.js

Fixing default origin energy limit 10,000,000 (1e7)

Fixing default origin energy limit

---

README.md

Adds a Recent History section in the README

Recent history in README

---

packages/tronwrap/index.js

reversing energy limit

---

README.md
packages/tronbox/package.json

Includes https://github.com/tronprotocol/tron-box/pull/58
Increase version
Update TronWeb

Version 2.3.1

---

package.json
packages/tronbox/package.json
packages/tronwrap/index.js
packages/tronwrap/package.json
packages/truffle-core/lib/commands/migrate.js
packages/truffle-deployer/index.js
packages/truffle-deployer/src/actions/deploy.js
packages/truffle-migrate/index.js

This fixes an issue deploying to mainnet, due — most likely — to latency issues, adding a loop during the retrieving of the new contract, trying again for 10 times any 500ms.

Fix get contract

---

packages/tronbox/package.json
packages/truffle-compile/index.js
packages/truffle-compile/messages.js
packages/truffle-compile/parser.js

This removes an annoying warning about compiler not ready for production.

Remove compiler warnings

---

packages/tronbox/package.json
packages/tronwrap/index.js
packages/truffle-core/lib/commands/build.js
packages/truffle-core/lib/commands/compile.js
packages/truffle-core/lib/commands/console.js
packages/truffle-core/lib/commands/create.js
packages/truffle-core/lib/commands/debug.js
packages/truffle-core/lib/commands/develop.js
packages/truffle-core/lib/commands/digest.js
packages/truffle-core/lib/commands/exec.js
packages/truffle-core/lib/commands/init.js
packages/truffle-core/lib/commands/install.js
packages/truffle-core/lib/commands/migrate.js
packages/truffle-core/lib/commands/networks.js
packages/truffle-core/lib/commands/opcode.js
packages/truffle-core/lib/commands/publish.js
packages/truffle-core/lib/commands/serve.js
packages/truffle-core/lib/commands/test.js
packages/truffle-core/lib/commands/version.js
packages/truffle-core/lib/commands/watch.js

This allows managing errors and reverts when triggering a smart contract, during testing.

Manage error triggering contracts during tests

---

packages/tronbox/package.json

Updating TronWeb to 2.1.14

---

packages/tronbox/package.json
packages/tronwrap/constants.js
packages/tronwrap/index.js
packages/truffle-deployer/src/actions/deploy.js

Updating to latest version of TronWeb and adding some minor change for compatibility.

Updating to latest TronWeb

---

package.json
packages/tronbox/package.json
packages/tronwrap/index.js
packages/truffle-core/lib/commands/version.js

This update to latest TronWeb which fixes the result when there are errors.

Fix errors in triggercontract

---

packages/tronwrap/index.js
packages/truffle-artifactor/package.json
packages/truffle-config/package.json
packages/truffle-contract/package.json
packages/truffle-core/package.json

If the userFeePercentage is set to 0, it was defaulted to 100.

Fix def user fee percentage if 0

---

README.md
packages/tronbox/package.json

Minore update

---

packages/tron-solc/package.json
packages/truffle-workflow-compile/package.json

Fix vulnerability with `lodash` 4.17.10

Fix vulnerability

---

README.md

Moving icon on the right

---

README.md

Reduce icon

---

README.md
packages/tronbox/package.json

Updating TronWeb to version 2.3.2.

Update tronweb to 2.3.2

---

packages/tron-solc/index.js
packages/tronbox/package.json
packages/tronwrap/index.js

This uses compiler version3 as default.

Using solc-3 as default
